parameters:
  - name: NightlyFlag
    type: string
    values:
      - ' '
      - --nightly
    default: ' '

jobs:

- job: GetReleaseVersion
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    # This has to be done separately because VSTS inexplicably
    # exits the script block after `npm ci` completes.
    - script: |
        cd script/vsts
        npm ci
      displayName: npm ci
    - script: node script/vsts/get-release-version.js ${{ parameters.NightlyFlag }}
      name: Version
      env:
        REPO_OWNER: $(REPO_OWNER)
        NIGHTLY_RELEASE_REPO: $(NIGHTLY_RELEASE_REPO)
