parameters:
  - name: NightlyFlag
    type: string
    values:
      - ' '
      - --nightly
    default: ' '

jobs:

- job: GetReleaseVersion
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - script: |
        cd script/vsts
        npm ci
        node get-release-version.js ${{ parameters.NightlyFlag }}
      name: Version
      env:
        REPO_OWNER: $(REPO_OWNER)
        NIGHTLY_RELEASE_REPO: $(NIGHTLY_RELEASE_REPO)
