jobs:
  - job: macOS_tests_github
    displayName: macOS Tests github
    dependsOn: macOS_build
    timeoutInMinutes: 180
    pool:
      vmImage: macos-10.15
    variables:
      ATOM_PACKAGES_TO_TEST: 'github'
      ATOM_RESOURCE_PATH: $(Build.SourcesDirectory)
      ATOM_RUN_PACKAGE_TESTS: 'true'
      CI: true
      MOCHA_TIMEOUT: 60000
      UNTIL_TIMEOUT: 60000
    steps:
      - template: ./preparation.yml

      - template: ./cache.yml
        parameters:
          OS: macos

      # The artifact caching task does not work on forks, so we need to
      # bootstrap again for pull requests coming from forked repositories.
      - template: ./bootstrap.yml

      - template: ./download-unzip.yml
        parameters:
          artifacts:
            - atom-mac.zip
            - atom-mac-symbols.zip

      - template: ./test.yml
        parameters:
          UseBundledResources: true
