# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr:
- none

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo vars: "$string" "$string2" "$string3"
  displayName: 'echo with double quotes around each var, pass in env block; string: $(string), string3: variables.string3'
  env: { string: $(string), string3: variables.string3 }

- script: |
    echo vars: $string $string2 $string3
  displayName: 'no quotes; string: $(string), string3: variables.string3'
  env: { string: $(string), string3: variables.string3 }

- script: |
    echo vars: "$string" "$string2" "$string3"
  displayName: 'no env, double quoting each individual var; echo "$string" "$string2" "$string3"'

- script: |
    echo vars: $string $string2 $string3
  displayName: 'no env, no quote marks'

- script: |
    echo vars: SET: $SET, SET_SECRET: $SET_SECRET, notset: $notset
  displayName: 'no env; echo $SET, $SET_SECRET and $notset'

- script: |
    echo vars: SET: $SET, SET_SECRET: $SET_SECRET, notset: $notset
  displayName: 'passed using $(macro) syntax in the env block: $SET, $SET_SECRET and $notset'
  env: {SET: $(SET), SET_SECRET: $(SET_SECRET), notset: $(NOTSET) }

- script: |
    echo vars: SET: $SET, SET_SECRET: $SET_SECRET, notset: $notset
  displayName: 'passed using \$\{\{ template \}\} variable syntax in the env block: SET, SET_SECRET and notset'
  env: 
   SET: ${{ variables.SET }}
   SET_SECRET: ${{ variables.SET_SECRET }}
   notset: ${{ variables.NOTSET }}