jobs:
  - job: macOS_build
    displayName: macOS Build
    dependsOn: GetReleaseVersion
    timeoutInMinutes: 180

    variables:
      ReleaseVersion: $[ dependencies.GetReleaseVersion.outputs['Version.ReleaseVersion'] ]
      IsReleaseBranch: $[ dependencies.GetReleaseVersion.outputs['Version.IsReleaseBranch'] ]
      IsSignedZipBranch: $[ dependencies.GetReleaseVersion.outputs['Version.IsSignedZipBranch'] ]
      RunCoreMainTests: true
    pool:
      vmImage: macos-10.15

    steps:
      - template: templates/preparation.yml

      - template: templates/cache.yml
        parameters:
          OS: macos

      - template: templates/bootstrap.yml

      - template: templates/build.yml

      - script: |
          cp $(Build.SourcesDirectory)/out/*.zip $(Build.ArtifactStagingDirectory)
        displayName: Stage Artifacts

      - template: templates/publish.yml
        parameters:
          artifacts:
            - fileName: atom-mac.zip
              fileDir: $(Build.ArtifactStagingDirectory)
              condition: succeeded()
            - fileName: atom-mac-symbols.zip
              fileDir: $(Build.ArtifactStagingDirectory)
              condition: succeeded()
            - fileName: atom-api.json
              fileDir: $(Build.SourcesDirectory)/docs/output
              condition: succeeded()

  # Import "macOS_tests_github" job
  - template: templates/macos-tests-github.yml
