jobs:
  - job: macOS_build
    displayName: macOS Build
    dependsOn: GetReleaseVersion
    timeoutInMinutes: 180

    variables:
      ReleaseVersion: $[ dependencies.GetReleaseVersion.outputs['Version.ReleaseVersion'] ]
      IsReleaseBranch: $[ dependencies.GetReleaseVersion.outputs['Version.IsReleaseBranch'] ]
      IsSignedZipBranch: $[ dependencies.GetReleaseVersion.outputs['Version.IsSignedZipBranch'] ]
      RunCoreMainTests: true
    pool:
      vmImage: macos-10.14

    steps:
      - template: templates/preparation.yml

      - template: templates/cache.yml
        parameters:
          OS: macos

      - template: templates/bootstrap.yml
